apiVersion: v2
name: synapse-launchpad
description: AI-powered startup matchmaking platform with behavioral science optimization
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - ai
  - startup
  - matchmaking
  - behavioral-science
maintainers:
  - name: Synapse LaunchPad Team
    email: devops@synapse-launchpad.com