apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.api.name }}
  labels:
    app: {{ .Values.api.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.api.name }}
      release: {{ .Release.Name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: {{ .Values.api.name }}
        release: {{ .Release.Name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Values.api.name }}
          image: "{{ .Values.global.imageRegistry }}/{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          env:
            - name: NODE_ENV
              value: {{ .Values.global.environment }}
            - name: PORT
              value: "8000"
            - name: DATABASE_URL
              value: "postgresql://postgres:$(DATABASE_PASSWORD)@{{ .Release.Name }}-postgresql:5432/synapse_db"
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: synapse-db-credentials
                  key: password
            - name: REDIS_URL
              value: "redis://:$(REDIS_PASSWORD)@{{ .Release.Name }}-redis-master:6379"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: synapse-redis-credentials
                  key: password
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: synapse-api-credentials
                  key: jwt-secret
            - name: CRUNCHBASE_KEY
              valueFrom:
                secretKeyRef:
                  name: synapse-api-credentials
                  key: crunchbase-key
            - name: LINKEDIN_TOKEN
              valueFrom:
                secretKeyRef:
                  name: synapse-api-credentials
                  key: linkedin-token
            - name: NEWSAPI_KEY
              valueFrom:
                secretKeyRef:
                  name: synapse-api-credentials
                  key: newsapi-key
            - name: STRIPE_SECRET
              valueFrom:
                secretKeyRef:
                  name: synapse-api-credentials
                  key: stripe-secret
            - name: STRIPE_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: synapse-api-credentials
                  key: stripe-webhook-secret
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: synapse-monitoring-credentials
                  key: sentry-dsn
            - name: ML_PARTNER_MATCHING_URL
              value: "http://{{ .Values.partnerRecommender.name }}:{{ .Values.partnerRecommender.service.port }}"
            - name: ML_CAMPAIGN_GENERATOR_URL
              value: "http://{{ .Values.campaignGenerator.name }}:{{ .Values.campaignGenerator.service.port }}"
            - name: ANALYTICS_URL
              value: "http://{{ .Values.analytics.name }}:{{ .Values.analytics.service.port }}"
            - name: DATA_PIPELINE_URL
              value: "http://{{ .Values.dataPipeline.name }}:{{ .Values.dataPipeline.service.port }}"
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
      {{- with .Values.api.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}