apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.campaignGenerator.name }}
  labels:
    app: {{ .Values.campaignGenerator.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.campaignGenerator.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.campaignGenerator.name }}
      release: {{ .Release.Name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: {{ .Values.campaignGenerator.name }}
        release: {{ .Release.Name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Values.campaignGenerator.name }}
          image: "{{ .Values.global.imageRegistry }}/{{ .Values.campaignGenerator.image.repository }}:{{ .Values.campaignGenerator.image.tag }}"
          imagePullPolicy: {{ .Values.campaignGenerator.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          env:
            - name: ENVIRONMENT
              value: {{ .Values.global.environment }}
            - name: PORT
              value: "8000"
            - name: REDIS_URL
              value: "redis://:$(REDIS_PASSWORD)@{{ .Release.Name }}-redis-master:6379"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: synapse-redis-credentials
                  key: password
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: synapse-ai-credentials
                  key: openai-api-key
            - name: OPENAI_MODEL
              value: "gpt-4o"
            - name: OPENAI_MAX_TOKENS
              value: "4096"
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: synapse-monitoring-credentials
                  key: sentry-dsn
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            {{- toYaml .Values.campaignGenerator.resources | nindent 12 }}
      {{- with .Values.campaignGenerator.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.campaignGenerator.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.campaignGenerator.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}