apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.marketPulseScanner.name }}
  labels:
    app: {{ .Values.marketPulseScanner.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.marketPulseScanner.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.marketPulseScanner.name }}
      release: {{ .Release.Name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: {{ .Values.marketPulseScanner.name }}
        release: {{ .Release.Name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Values.marketPulseScanner.name }}
          image: "{{ .Values.global.imageRegistry }}/{{ .Values.marketPulseScanner.image.repository }}:{{ .Values.marketPulseScanner.image.tag }}"
          imagePullPolicy: {{ .Values.marketPulseScanner.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          env:
            - name: ENVIRONMENT
              value: {{ .Values.global.environment }}
            - name: PORT
              value: "8000"
            - name: DATABASE_URL
              value: "postgresql://postgres:$(DATABASE_PASSWORD)@{{ .Release.Name }}-postgresql:5432/synapse_db"
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: synapse-db-credentials
                  key: password
            - name: REDIS_URL
              value: "redis://:$(REDIS_PASSWORD)@{{ .Release.Name }}-redis-master:6379"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: synapse-redis-credentials
                  key: password
            - name: CRUNCHBASE_KEY
              valueFrom:
                secretKeyRef:
                  name: synapse-api-credentials
                  key: crunchbase-key
            - name: LINKEDIN_TOKEN
              valueFrom:
                secretKeyRef:
                  name: synapse-api-credentials
                  key: linkedin-token
            - name: NEWSAPI_KEY
              valueFrom:
                secretKeyRef:
                  name: synapse-api-credentials
                  key: newsapi-key
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: synapse-monitoring-credentials
                  key: sentry-dsn
            - name: SCAN_INTERVAL_MINUTES
              value: "30"
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            {{- toYaml .Values.marketPulseScanner.resources | nindent 12 }}
      {{- with .Values.marketPulseScanner.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.marketPulseScanner.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.marketPulseScanner.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}