{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Values.externalSecrets.secretStore.name }}
spec:
  provider:
    twentyfirst:
      # 21st.dev provider configuration
      auth:
        secretRef:
          apiKeySecretRef:
            name: twentyfirst-api-key
            key: api-key
---
{{- range .Values.externalSecrets.secrets }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .name }}
spec:
  refreshInterval: {{ .refreshInterval }}
  secretStoreRef:
    name: {{ $.Values.externalSecrets.secretStore.name }}
    kind: {{ $.Values.externalSecrets.secretStore.kind }}
  target:
    name: {{ .name }}
    creationPolicy: Owner
  data:
  {{- range .data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteRef.key }}
  {{- end }}
---
{{- end }}
{{- end }}